package moomaui.domain;
public class Machines {
	public static IMooreMachine automaton1(){
		MooreMachine machine = new MooreMachine();
		machine.setMachineName("automaton1");
		State V0 = new State("V0");
		V0.setOutput((VendingEnvironment env) -> env.notify("V0"));
		machine.addState(V0);
		State V20Bo = new State("V20Bo");
		V20Bo.setOutput((VendingEnvironment env) -> env.notify("V20Bo"));
		machine.addState(V20Bo);
		State V0To = new State("V0To");
		V0To.setOutput((VendingEnvironment env) -> env.notify("V0ToD"));
		machine.addState(V0To);
		State V0Bo = new State("V0Bo");
		V0Bo.setOutput((VendingEnvironment env) -> env.notify("V0Bo"));
		machine.addState(V0Bo);
		State V20 = new State("V20");
		V20.setOutput((VendingEnvironment env) -> env.notify("V20"));
		machine.addState(V20);
		State V30Be = new State("V30Be");
		V30Be.setOutput((VendingEnvironment env) -> env.notify("V30Be"));
		machine.addState(V30Be);
		State V10Bo = new State("V10Bo");
		V10Bo.setOutput((VendingEnvironment env) -> env.notify("V10Bo"));
		machine.addState(V10Bo);
		State V10 = new State("V10");
		V10.setOutput((VendingEnvironment env) -> env.notify("V10"));
		machine.addState(V10);
		State V30Bo = new State("V30Bo");
		V30Bo.setOutput((VendingEnvironment env) -> env.notify("V30Bo"));
		machine.addState(V30Bo);
		State V0ToD = new State("V0ToD");
		V0ToD.setOutput((VendingEnvironment env) -> env.notify("V0ToD"));
		machine.addState(V0ToD);
		State V0Be = new State("V0Be");
		V0Be.setOutput((VendingEnvironment env) -> env.notify("V0Be"));
		machine.addState(V0Be);
		State V30 = new State("V30");
		V30.setOutput((VendingEnvironment env) -> env.notify("V30"));
		machine.addState(V30);
		State V10Be = new State("V10Be");
		V10Be.setOutput((VendingEnvironment env) -> env.notify("V10Be"));
		machine.addState(V10Be);
		State V20Be = new State("V20Be");
		V20Be.setOutput((VendingEnvironment env) -> env.notify("V20Be"));
		machine.addState(V20Be);
		State V0BeD = new State("V0BeD");
		V0BeD.setOutput((VendingEnvironment env) -> env.notify("V0BeD"));
		machine.addState(V0BeD);
		Transition t1 = new Transition (V0,V10,"10");
		machine.addTransition(t1);
		Transition t2 = new Transition (V10,V20,"10");
		machine.addTransition(t2);
		Transition t3 = new Transition (V20,V30,"10");
		machine.addTransition(t3);
		Transition t4 = new Transition (V20,V0Be,"20");
		machine.addTransition(t4);
		Transition t5 = new Transition (V30,V0BeD,"20");
		machine.addTransition(t5);
		Transition t6 = new Transition (V30,V0Bo,"30");
		machine.addTransition(t6);
		Transition t7 = new Transition (V0BeD,V10Be,"10");
		machine.addTransition(t7);
		Transition t8 = new Transition (V0Be,V10Be,"10");
		machine.addTransition(t8);
		Transition t9 = new Transition (V10Be,V20Be,"10");
		machine.addTransition(t9);
		Transition t10 = new Transition (V20Be,V30Be,"10");
		machine.addTransition(t10);
		Transition t11 = new Transition (V30Be,V0To,"30");
		machine.addTransition(t11);
		Transition t12 = new Transition (V0Bo,V10Bo,"10");
		machine.addTransition(t12);
		Transition t13 = new Transition (V10Bo,V20Bo,"10");
		machine.addTransition(t13);
		Transition t14 = new Transition (V20Bo,V30Bo,"10");
		machine.addTransition(t14);
		Transition t15 = new Transition (V20Bo,V0To,"20");
		machine.addTransition(t15);
		Transition t16 = new Transition (V30Bo,V0ToD,"20");
		machine.addTransition(t16);
		machine.setInitialState(V0);
		return machine;
	}
}